#pragma once

#include <stdint.h>

typedef struct {
  uint8_t folder;
  uint8_t track;
  const char* title;
  const char* artist;
  const char* album;
  uint16_t length; // seconds
} Song;

#define SONG_COUNT 196

const Song songs[SONG_COUNT] PROGMEM = {
  { 1, 1, "A Room Up In The Sky (feat. The Marías)", "Eyedress/The Marías", "A Room Up In The Sky (feat. The Marías)", 167 },
  { 1, 2, "Afterthought", "Tame Impala", "Deadbeat", 243 },
  { 1, 3, "Amerika", "Rammstein", "Reise, Reise", 258 },
  { 1, 4, "Are You Bored Yet? (feat. Clairo)", "Wallows/Clairo", "Nothing Happens", 206 },
  { 1, 5, "Ausländer", "Rammstein", "Rammstein", 280 },
  { 1, 6, "Blue Hair", "TV Girl", "Death of a Party Girl", 219 },
  { 1, 7, "Brian is the Most Beautiful", "Memo Boy", "Songs & Demos 2015-2017", 225 },
  { 1, 8, "Brokendate", "Com Truise", "Galactic Melt", 309 },
  { 1, 9, "Can I Call You Tonight?", "Dayglow", "Fuzzybrain", 299 },
  { 1, 10, "Chamber Of Reflection", "Mac DeMarco", "Salad Days", 231 },
  { 1, 11, "Children", "Robert Miles", "Children (Dance Vault Mixes)", 243 },
  { 1, 12, "Cool To Be Unhappy", "Elephant Castle", "Cool To Be Unhappy", 269 },
  { 1, 13, "Dancing with my phone", "HYBS", "Making Steak", 225 },
  { 1, 14, "Deutschland", "Rammstein", "Rammstein", 562 },
  { 1, 15, "Du hast", "Rammstein", "Sehnsucht (Remastered 2023)", 235 },
  { 1, 16, "Easy Love", "Goldensuns", "Easy Love", 243 },
  { 1, 17, "Eifersucht", "Rammstein", "Sehnsucht (Remastered 2023)", 215 },
  { 1, 18, "End Of Summer", "Tame Impala", "Deadbeat", 567 },
  { 1, 19, "Engel", "Rammstein", "Sehnsucht", 265 },
  { 1, 20, "Ethereal Connection", "Tame Impala", "Deadbeat", 463 },
  { 1, 21, "Fainted", "Narvent", "Fainted", 250 },
  { 1, 22, "Feuer frei!", "Rammstein", "Mutter", 190 },
  { 1, 23, "Gilded Lily", "Cults", "Offering", 214 },
  { 1, 24, "Go Higher", "HYBS", "Making Steak", 206 },
  { 1, 25, "God Is", "Kanye West", "JESUS IS KING", 203 },
  { 1, 26, "Golden Brown - Slowed Down Version", "The Stranglers", "Golden Brown", 248 },
  { 1, 27, "Goth (Slowed + Reverb)", "Sidewalks and Skeletons", "Goth (Slowed + Reverb)", 252 },
  { 1, 28, "Hard Parade", "LiterallyMe", "Hard Parade", 163 },
  { 1, 29, "Hidden Star", "Crepes", "Hidden Star", 215 },
  { 1, 30, "High on My Own", "Tempesst", "Must Be a Dream", 230 },
  { 1, 31, "Holding Out For You", "Pond", "Man It Feels Like Space Again", 283 },
  { 1, 32, "I Love You So", "The Walters", "I Love You So", 160 },
  { 1, 33, "Ich will", "Rammstein", "Mutter", 245 },
  { 1, 34, "If I Could Find You (Eternity)", "The Holydrug Couple", "Moonlust", 180 },
  { 1, 35, "Judas", "Lady Gaga", "Born This Way (International Special Edition Version)", 334 },
  { 1, 36, "Keine Lust", "Rammstein", "Reise, Reise", 359 },
  { 1, 37, "Lamb's Wool", "Foster The People", "Lamb's Wool", 282 },
  { 1, 38, "Links 2 3 4", "Rammstein", "Mutter", 216 },
  { 1, 39, "Little Dark Age", "MGMT", "Little Dark Age", 310 },
  { 1, 40, "Loser", "Tame Impala", "Deadbeat", 267 },
  { 1, 41, "Luxury", "Azealia Banks", "Broke with Expensive Taste", 165 },
  { 1, 42, "Mein Herz brennt", "Rammstein", "Mutter", 306 },
  { 1, 43, "Melting", "Kali Uchis", "Por Vida", 209 },
  { 1, 44, "Memory Reboot - Slowed", "VØJ/Narvent", "Memory Reboot", 236 },
  { 1, 45, "Metamodernity", "Vansire", "Metamodernity", 162 },
  { 1, 46, "Middy Titty", "Paulie Leparik", "Neon Daydream", 94 },
  { 1, 47, "Modern Day Living", "Jermango Dreaming", "Modern Day Living", 263 },
  { 1, 48, "Moskau", "Rammstein", "Reise, Reise", 256 },
  { 1, 49, "My Old Ways", "Tame Impala", "Deadbeat", 319 },
  { 1, 50, "Nervous", "The Neighbourhood", "Hard To Imagine The Neighbourhood Ever Changing", 250 },
  { 1, 51, "No More Lies", "Thundercat/Tame Impala", "No More Lies", 327 },
  { 1, 52, "No Reply", "Tame Impala", "Deadbeat", 216 },
  { 1, 53, "Reality/Nostalgia", "Pink Skies", "Reality/Nostalgia", 233 },
  { 1, 54, "Not Into You", "Brooksie", "Not Into You", 187 },
  { 1, 55, "Not My World", "Tame Impala", "Deadbeat", 255 },
  { 1, 56, "ON DAT BXTCH! - SUPER SLOWED - INSTRUMENTAL", "velours", "ON DAT BXTCH!", 160 },
  { 1, 57, "Oblivion", "Tame Impala", "Deadbeat", 270 },
  { 1, 58, "Obsolete", "Tame Impala", "Deadbeat", 265 },
  { 1, 59, "Ohne dich", "Rammstein", "Reise, Reise", 341 },
  { 1, 60, "Origami", "The Rare Occasions", "Big Whoop", 174 },
  { 1, 61, "Piece Of Heaven", "Tame Impala", "Deadbeat", 286 },
  { 1, 62, "Push The Feeling On - Slowed+Reverb", "Zarazzie", "Push The Feeling On (Slowed+Reverb)", 274 },
  { 1, 63, "Quarterback", "Wallows", "Quarterback", 183 },
  { 1, 64, "Radio", "Rammstein", "Rammstein", 290 },
  { 1, 65, "Remember When", "Wallows", "Nothing Happens", 155 },
  { 1, 66, "Resonance Nails (Remix)", "Sqizzo", "Resonance Nails (Remix)", 214 },
  { 1, 67, "Rosenrot", "Rammstein", "Rosenrot", 239 },
  { 1, 68, "Sandstorm", "Darude", "Before the Storm, Special Edition", 232 },
  { 1, 69, "Saturnine", "Mystery Jets", "Curve Of The Earth", 381 },
  { 1, 70, "Scrawny", "Wallows", "Nothing Happens", 167 },
  { 1, 71, "See You On Monday (You're Lost)", "Tame Impala", "Deadbeat", 216 },
  { 1, 72, "Sehnsucht", "Rammstein", "Sehnsucht (Remastered 2023)", 244 },
  { 1, 73, "Shook", "Goldensuns", "Shook", 191 },
  { 1, 74, "SimpsonWave1995", "FrankJavCee", "FrankJavCee Collection, Vol. 1, Pt. II", 141 },
  { 1, 75, "Sitting Up On Our Crane", "Pond", "Man It Feels Like Space Again", 360 },
  { 1, 76, "Sky So Blue", "Hot Flash Heat Wave", "Sky So Blue", 262 },
  { 1, 77, "Sky", "Playboi Carti", "Whole Lotta Red", 192 },
  { 1, 78, "Somebody That I Used To Know", "Gotye/Kimbra", "Making Mirrors", 243 },
  { 1, 79, "Something About You", "Eyedress/Dent May", "Mulholland Drive", 163 },
  { 1, 80, "Sonne", "Rammstein", "Mutter", 252 },
  { 1, 81, "Space Song", "Beach House", "Depression Cherry", 320 },
  { 1, 82, "Spieluhr", "Rammstein", "Mutter", 286 },
  { 1, 83, "Staring", "Tipling Rock", "Staring", 208 },
  { 1, 84, "Stress Relief", "late night drive home", "Am I sinking or Am I swimming?", 207 },
  { 1, 85, "Sugar", "Beach Fossils", "Somersault", 204 },
  { 1, 86, "Tangerine", "Beach Fossils", "Somersault", 194 },
  { 1, 87, "The Bay", "Yot Club", "The Bay", 167 },
  { 1, 88, "The Weather", "Pond", "The Weather", 235 },
  { 1, 89, "Tier", "Rammstein", "Sehnsucht (Remastered 2023)", 226 },
  { 1, 90, "Tranz", "Gorillaz", "The Now Now", 174 },
  { 1, 91, "U Weren't Here I Really Miss You", "Cult Member/Mia Martina", "U Weren't Here I Really Miss You", 160 },
  { 1, 92, "We're Finally Landing", "Home", "Before the Night", 272 },
  { 1, 93, "What You Know", "Two Door Cinema Club", "Tourist History", 191 },
  { 1, 94, "drifting", "Night Tapes", "drifting", 212 },
  { 1, 95, "endlessly", "Chanpan", "endlessly", 182 },
  { 1, 96, "fading faith - Slowed", "crier", "fading faith", 216 },
  { 1, 97, "poster boy", "2hollis", "2", 121 },
  { 1, 98, "pulsebreaker - slowed", "OTVphonk/ZERTAL", "pulsebreaker", 131 },
  { 2, 1, "16 Dimensions", "Albert Newton", "Twin Earth", 232 },
  { 2, 2, "affection", "BETWEEN FRIENDS", "we just need some time together", 235 },
  { 2, 3, "So Cold", "Balu Brigada", "Portal", 201 },
  { 2, 4, "L.I.N.E.", "Beach Fossils", "L.I.N.E.", 191 },
  { 2, 5, "May 1st", "Beach Fossils", "Somersault", 178 },
  { 2, 6, "Tangerine", "Beach Fossils", "Somersault", 194 },
  { 2, 7, "That’s All for Now", "Beach Fossils", "Somersault", 192 },
  { 2, 8, "Myth", "Beach House", "Bloom", 258 },
  { 2, 9, "PPP", "Beach House", "Depression Cherry", 368 },
  { 2, 10, "Silver Soul", "Beach House", "Teen Dream", 298 },
  { 2, 11, "Wildflower", "Beach House", "Depression Cherry", 219 },
  { 2, 12, "Set it on Fire", "Blood Cultures", "LUNO", 213 },
  { 2, 13, "My Love", "Butter Bath, Jermango Dreaming", "My Love", 209 },
  { 2, 14, "Change Your Mind", "CASTLEBEAT", "CASTLEBEAT", 297 },
  { 2, 15, "East Coast", "CASTLEBEAT", "Melodrama", 277 },
  { 2, 16, "Constellations", "CD Ghost", "Constellations", 198 },
  { 2, 17, "Undercurrent", "CD Ghost", "Dreams We Share", 151 },
  { 2, 18, "Can I Call You Tonight? / Quarterback", "Cal in Red", "Can I Call You Tonight? / Quarterback", 195 },
  { 2, 19, "Out to Sea", "Caraml", "Out to Sea", 294 },
  { 2, 20, "Heavenly", "Cigarettes After Sex", "Cry", 286 },
  { 2, 21, "Dream Girl", "Crisaunt", "Dream Girl", 179 },
  { 2, 22, "Vanished", "Crystal Castles", "Crystal Castles", 243 },
  { 2, 23, "Always Forever", "Cults", "Static", 223 },
  { 2, 24, "Kimosabè", "DOPE LEMON", "Kimosabè", 276 },
  { 2, 25, "Close To You", "Dayglow", "Harmony House", 194 },
  { 2, 26, "Don't U Think", "Dook Walt Jr.", "15Th Floor", 219 },
  { 2, 27, "welcome and goodbye", "Dream, Ivory", "welcome and goodbye", 140 },
  { 2, 28, "Could It Be?", "Elan Noon", "Have a Spirit Filled", 302 },
  { 2, 29, "Cherry Blossom", "Empire Of The Sun", "Ask That God", 207 },
  { 2, 30, "Way To Go", "Empire Of The Sun", "Two Vines (Deluxe)", 192 },
  { 2, 31, "We Are The People", "Empire Of The Sun", "Walking On A Dream (10th Anniversary Edition)", 267 },
  { 2, 32, "The Outro", "Estie Lorie", "The Outro", 245 },
  { 2, 33, "Change My View (feat. Elvia & Boaty)", "Eyedress, Elvia, Boaty", "Stoner", 133 },
  { 2, 34, "Never See Your Face Again (feat. Strawberry Guy)", "Eyedress, Strawberry Guy", "Stoner", 174 },
  { 2, 35, "A Dream of You", "Far Caspian", "A Dream of You", 258 },
  { 2, 36, "Blue", "Far Caspian", "Between Days", 205 },
  { 2, 37, "Imagination", "Foster The People", "Imagination", 256 },
  { 2, 38, "Lotus Eater", "Foster The People", "Sacred Hearts Club", 182 },
  { 2, 39, "Under The Moon", "Foster The People", "In The Darkest Of Nights, Let The Birds Sing", 279 },
  { 2, 40, "Empty", "Goldensuns, Warpaint", "Empty", 197 },
  { 2, 41, "Two Weeks", "Grizzly Bear", "Veckatimest", 246 },
  { 2, 42, "Prune, You Talk Funny", "Gus Dapperton", "Prune, You Talk Funny", 212 },
  { 2, 43, "She Needs Him", "Her's", "Invitation to Her's", 314 },
  { 2, 44, "Too Sweet", "Hozier", "Unreal Unearth: Unaired", 251 },
  { 2, 45, "American Spirits", "Inner Wave", "III", 170 },
  { 2, 46, "Breeze", "Jermango Dreaming", "Breeze", 233 },
  { 2, 47, "Looking Out for You", "Joy Again", "Looking Out for You", 179 },
  { 2, 48, "Finding Peace of Mind", "Kainalu", "Lotus Gate", 221 },
  { 2, 49, "Words I Never Heard", "Kirk Francis", "Words I Never Heard", 130 },
  { 2, 50, "Italo Disco", "Last Dinosaurs", "Yumeno Garden", 226 },
  { 2, 51, "Chick'n Tenders", "Late Again", "Clearly It's All Staged", 171 },
  { 2, 52, "Krystal", "Matt Maltese", "Krystal", 220 },
  { 2, 53, "Blossoms", "Meltt", "Eternal Embers", 205 },
  { 2, 54, "The Absent Sea", "Meltt", "Eternal Embers", 306 },
  { 2, 55, "The Fire", "Meltt", "Eternal Embers", 281 },
  { 2, 56, "Sugar", "Men I Trust", "Untourable Album", 176 },
  { 2, 57, "Someone, Someone Real", "Nick Wagen, crêpe girl", "Someone, Someone Real", 239 },
  { 2, 58, "Days", "No Vacation", "Days", 320 },
  { 2, 59, "forever, with you", "Paradise Blossom", "forever, with you", 176 },
  { 2, 60, "Fine Madeline", "Plums", "Jen", 139 },
  { 2, 61, "Put Your Records On", "Ritt Momney", "Put Your Records On", 210 },
  { 2, 62, "Never Ending Summer", "Sleepy Soul", "Never Ending Summer", 186 },
  { 2, 63, "Human Emotion", "Small Forward", "Human Emotion", 230 },
  { 2, 64, "Tearjerker", "Small Forward", "Tearjerker", 250 },
  { 2, 65, "Panoramic View", "Spaceface", "Anemoia", 214 },
  { 2, 66, "Birch Tree", "Strawberry Guy", "Taking My Time to Be", 280 },
  { 2, 67, "F Song", "Strawberry Guy", "F Song", 224 },
  { 2, 68, "Intermission", "Strawberry Guy", "Taking My Time to Be", 110 },
  { 2, 69, "Mrs Magic", "Strawberry Guy", "Mrs Magic", 208 },
  { 2, 70, "Stay In This Moment", "Strawberry Guy", "Sun Outside My Window", 183 },
  { 2, 71, "What Would I Do?", "Strawberry Guy", "What Would I Do?", 234 },
  { 2, 72, "Without You", "Strawberry Guy", "Without You", 228 },
  { 2, 73, "How Come?", "Stray Fossa", "With You For Ever", 300 },
  { 2, 74, "Swells", "Stray Fossa", "Swells", 232 },
  { 2, 75, "Anymore", "Surf Rock Is Dead", "Anymore", 197 },
  { 2, 76, "Lovers Rock", "TV Girl", "French Exit", 214 },
  { 2, 77, "Dracula", "Tame Impala", "Dracula", 205 },
  { 2, 78, "The Adults Are Talking", "The Strokes", "The New Abnormal", 309 },
  { 2, 79, "Always Tomorrow", "Tokyo Tea Room", "Dream Room", 222 },
  { 2, 80, "Designer", "Tokyo Tea Room", "Dream Room", 226 },
  { 2, 81, "Forever out of Time", "Tokyo Tea Room", "Dream Room", 170 },
  { 2, 82, "Things Are Changing", "Tokyo Tea Room", "Dream Room", 230 },
  { 2, 83, "Eleven Weeks", "Vansire", "The Rolling, Driftless North", 185 },
  { 2, 84, "Halcyon Age", "Vansire", "Angel Youth", 193 },
  { 2, 85, "In Between", "WILLIS", "Locals 4", 148 },
  { 2, 86, "Bad Dream", "Wallows", "Model", 210 },
  { 2, 87, "Chandelier", "Will Paquin", "Chandelier", 127 },
  { 2, 88, "It's Almost Like You're Here", "Yndling", "Time Time Time (I'm in the Palm of Your Hand)", 232 },
  { 2, 89, "Fly Out West - Single Version", "Yot Club", "Fly Out West", 174 },
  { 2, 90, "did i tell u that i miss u", "adore", "did i tell u that i miss u", 114 },
  { 2, 91, "can't slow down", "almost monday", "DIVE", 175 },
  { 2, 92, "Home", "coldroses", "two", 198 },
  { 2, 93, "Why Can't You Be Mine", "coldroses", "Farewell", 193 },
  { 2, 94, "Feel It", "d4vd", "WITHERED", 157 },
  { 2, 95, "Sad Disco", "flipturn", "Shadowglow", 227 },
  { 2, 96, "Wasted Summers", "juju<3", "Wasted Summers", 130 },
  { 2, 97, "i was all over her", "salvia palth", "melanchole", 161 },
  { 2, 98, "7 Weeks & 3 Days", "yungatita", "Over You", 194 },
};
